<a href="https://colab.research.google.com/github/ARISHA123b/Numpy-For-Machine-Learning-/blob/main/Numpy_for_Machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,7]) # creating an array from list
print("1d array",arr_1d)

1d array [1 2 3 4 7]


In [ ]:
arr2_d = np.array([[1,2,3,4],[6,7,8,9]])
print("2d_array",arr2_d)

2d_array [[1 2 3 4]
 [6 7 8 9]]


In [ ]:
#LIST VS NUMPY ARRAY
py_list = [1,2,3,4]
print("python list multiplication",py_list*2)
np_array = np.array([1,2,3,4])
print("numpy array multiplication",np_array*2)

python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
numpy array multiplication [2 4 6 8]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ",time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("\n Numpy List operation time",time.time()-start)


 List operation time :  0.03833723068237305

 Numpy List operation time 0.002523183822631836


In [ ]:
### creating array from scratch
zeroes = np.zeros((3,4))
print("zereos array : \n",zeroes)

zereos array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
full = np.full((2,2),7)
full

array([[7, 7],
       [7, 7]])

In [ ]:
random = np.random.random((3,2))
random

array([[0.54032445, 0.36485951],
       [0.2318579 , 0.99282573],
       [0.81436144, 0.45492959]])

In [ ]:
sequence = np.arange(0,10,2)
sequence

array([0, 2, 4, 6, 8])

In [ ]:
### Vectors , Matrix , Tensors
vector = np.array([1,2,3])
vector
matrx = np.array([[1,2,3],[3,4,6]])
matrx

array([[1, 2, 3],
       [3, 4, 6]])

In [ ]:
tensor = np.array([[[1,2,43],[3,4,78]],[[9,89,2],[789,32,1]]])
tensor

array([[[  1,   2,  43],
        [  3,   4,  78]],

       [[  9,  89,   2],
        [789,  32,   1]]])

In [ ]:
#array properties
array = np.array([[1,2,3],
                 [3,8,9]])
print("Shape",array.shape)
print("Dimension",array.ndim)
print("Size",array.size)
print("DType",array.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64


In [ ]:
# array reshapping
arr = np.arange(12)
print("Original Array",arr)
reshaped = arr.reshape((3,4))
reshaped
flattened = reshaped.flatten()
flattened

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
raveled = reshaped.ravel() #returns view instead of a copy
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#transpose
trsnspose = reshaped.T
trsnspose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Numpy Array Operations

In [ ]:
arr = np.array([1,2,3,4,6,7,8,9,90])
print("Basic Slicing",arr[2:7])
print("With Step",arr[0:7:2])
print("Negative Slicing",arr[-2])

Basic Slicing [3 4 6 7 8]
With Step [1 3 6 8]
Negative Slicing 9


In [ ]:
arr_2d = np.array([[1,2,3],
                   [7,8,6],
                   [8,3,4]])
print("Specific Element",arr_2d[1,2])
print("Specific Element",arr_2d[2,2])
print("Specific Element",arr_2d[1])
print("Specific Element",arr_2d[:,0])

Specific Element 6
Specific Element 4
Specific Element [7 8 6]
Specific Element [1 7 8]


In [ ]:
unsorted = np.array([3,6,7,8,9,23])
print("Unsorted",np.sort(unsorted))

Unsorted [ 3  6  7  8  9 23]


In [ ]:
unsorted = np.array([[12, 89],[32, 23],[21, 23]])
print("Sorted 2d array:\n", np.sort(unsorted,axis = 0))

Sorted 2d array:
 [[12 23]
 [21 23]
 [32 89]]


In [ ]:
#Filtering
numbers = np.array([1,2,3,4,6,7,8,9,90])
even_numer = numbers[numbers %2==0]
print("Even numbers",even_numer)

Even numbers [ 2  4  6  8 90]


In [ ]:
#mask filteration
mask = numbers > 7
print(numbers[mask])

[ 8  9 90]


### Fancing indexing vs np.where


In [ ]:
indices = [0,2,3,4]
print(numbers[indices])
where_result = np.where(numbers>6)
print(where_result)

[1 3 4 6]
(array([5, 6, 7, 8]),)


In [ ]:
numbers =np.array([1,2,3,4,6,7,8])
condition_Array = np.where(numbers >6 , numbers*2,numbers)
print(condition_Array)

[ 1  2  3  4  6 14 16]


In [ ]:
#Adding & Removing Data
arr1 = np.array = [12,23,46,78]
arr2 = np.array = [12,33,23,11]
combined = np.concatenate((arr1,arr2)) #merge
combined

array([12, 23, 46, 78, 12, 33, 23, 11])

In [ ]:
# Array compatibility
import numpy as np
b = np.array([4,6,7])
c = np.array([3,2,1])
print("compatibility shapes",b.shape == c.shape)

compatibility shapes True


In [ ]:
original = np.array([[1,2],[3,4]]) #means when you vertically stack 1d array and become 2d vstack always add row
new_row = np.array([[7,8],[3,4]])
with_new_row = np.vstack((original,new_row))
print(original)
print(new_row)
print(with_new_row)
new_column = np.array([[7],[9]])
with_new_column = np.hstack((original,new_column)) #hstack adds new column
print("With new Column",with_new_column)

[[1 2]
 [3 4]]
[[7 8]
 [3 4]]
[[1 2]
 [3 4]
 [7 8]
 [3 4]]
With new Column [[1 2 7]
 [3 4 9]]


In [ ]:
#delete operation
arr = np.array([2,3,4,6,7,8])
deleted = np.delete(arr,[1,3])
deleted_1 = np.delete(arr,3)
print("deleted",deleted_1)
print("deleted",deleted)

deleted [2 3 4 7 8]
deleted [2 4 7 8]
